import { Accordion, Container, Text } from "@mantine/core";

const home = () => {
  return (
    <Container size="xl">
      <Accordion variant="separated">
        {terms.map((item) => {
          return (
            <Accordion.Item
              key={item.title.replace(/\s+/g, "-").toLowerCase()}
              value={item.title.replace(/\s+/g, "-").toLowerCase()}
            >
              <Accordion.Control>{item.title}</Accordion.Control>
              {item.content.map((item, index) => {
                return <Accordion.Panel key={index}>{item}</Accordion.Panel>;
              })}
            </Accordion.Item>
          );
        })}
      </Accordion>
      <Text color="dimmed" size="xs" align="right">
        Terms and Conditions were generated by ChatGPT
      </Text>
    </Container>
  );
};

export default home;

let terms = [
  {
    title: "1. Acceptance of Terms",
    content: [
      "By accessing or using this Website, you acknowledge that you have read, understood, and agree to be bound by these Terms, as well as our Privacy Policy, which is incorporated herein by reference. If you do not agree to these Terms or our Privacy Policy, you must not use this Website.",
    ],
  },
  {
    title: "2. Use of Website",
    content: [
      "You must be at least 18 years of age to use this Website. You agree that you will only use this Website for lawful purposes and in compliance with these Terms. You agree not to use this Website to:",
      "a. Harass, abuse, or harm another person or entity;",
      "b. Engage in fraudulent or deceptive activities;",
      "c. Violate any applicable laws or regulations;",
      "d. Infringe upon the intellectual property rights of others;",
      "e. Distribute viruses or other harmful computer code;",
      "f. Interfere with or disrupt the operation of this Website or the servers or networks used to make this Website available; or",
      "g. Engage in any other activity that we, in our sole discretion, deem to be inappropriate or that could harm our reputation.",
    ],
  },
  {
    title: "3. Products",
    content: [
      "We offer a variety of consumer electronics products for sale on this Website. We reserve the right to change the products available on this Website at any time and without notice. We also reserve the right to limit the quantities of any product that we offer.",
    ],
  },
  {
    title: "4. Prices and Payment",
    content: [
      "All prices on this Website are in USD and are subject to change at any time without notice. We make every effort to ensure that the prices listed on this Website are accurate, but we cannot guarantee that they are error-free. We reserve the right to correct any errors in pricing or product descriptions, even after you have placed your order.",
      "We accept various forms of payment, including credit cards, debit cards, and PayPal. You will be asked to provide your payment information at the time of purchase. By providing your payment information, you represent and warrant that you have the legal right to use the payment method you provided.",
    ],
  },
  {
    title: "5. Shipping and Delivery",
    content: [
      "We ship our products to most countries around the world. Shipping and delivery times will vary depending on your location and the shipping method you select. We will provide you with an estimated delivery date at the time of purchase, but we cannot guarantee delivery by that date.",
      "We are not responsible for any customs or import duties that may be charged on your order. It is your responsibility to pay any such fees.",
    ],
  },
  {
    title: "6. Returns and Refunds",
    content: [
      "We want you to be completely satisfied with your purchase. If for any reason you are not satisfied, you may return the product for a full refund within [Number of days] days of receipt. The product must be in its original packaging and in new condition.",
      "To initiate a return, please contact us at [Contact Email] to obtain a return authorization number. You will be responsible for the cost of return shipping.",
      "Once we receive your returned product, we will process your refund within [Number of days] days. Refunds will be issued to the original form of payment.",
    ],
  },
  {
    title: "7. Intellectual Property",
    content: [
      "This Website and all of its content, including but not limited to text, graphics, logos, images, and software, are the property of the Company or its licensors and are protected by United States and international copyright laws.",
      "You may not use, copy, reproduce, modify, distribute, transmit, or display any of the content on this Website without our prior written consent.",
    ],
  },
  {
    title: "8. Limitation of Liability",
    content: [
      "IN NO EVENT SHALL THE COMPANY OR ANY OF ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, SUPPLIERS, OR LICENSORS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THIS WEBSITE OR THE PRODUCTS SOLD ON THIS WEBSITE, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, WHETHER BASED ON CONTRACT, TORT, STRICT LIABILITY, OR ANY OTHER LEGAL THEORY, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.",
      "IN NO EVENT SHALL THE COMPANY’S TOTAL LIABILITY TO YOU FOR ALL DAMAGES, LOSSES, AND CAUSES OF ACTION ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THIS WEBSITE OR THE PRODUCTS SOLD ON THIS WEBSITE EXCEED THE AMOUNT PAID BY YOU FOR THE PRODUCT IN QUESTION.",
    ],
  },
  {
    title: "9. Indemnification",
    content: [
      "You agree to indemnify, defend, and hold harmless the Company and its affiliates, officers, directors, employees, agents, suppliers, and licensors from and against any and all claims, damages, losses, liabilities, and expenses (including but not limited to attorney’s fees) arising out of or in connection with your use of this Website or the products sold on this Website, your breach of these Terms, or your violation of any law or the rights of any third party.",
    ],
  },
  {
    title: "10. Termination",
    content: [
      "We may terminate your access to this Website at any time, for any reason, and without notice to you. Upon termination, you must immediately cease all use of this Website.",
    ],
  },
  {
    title: "11. Governing Law and Jurisdiction",
    content: [
      "These Terms and your use of this Website shall be governed by and construed in accordance with the laws of the state of [State], without giving effect to any principles of conflicts of law. Any legal action or proceeding arising out of or in connection with these Terms or your use of this Website shall be brought exclusively in the state or federal courts located in [City], [State], and you consent to the jurisdiction of such courts.",
    ],
  },
  {
    title: "12. Changes to Terms",
    content: [
      "We may revise these Terms at any time by updating this page. By using this Website, you agree to be bound by the current version of these Terms. It is your responsibility to periodically review these Terms to stay informed of any changes.",
    ],
  },
  {
    title: "13. Miscellaneous",
    content: [
      "These Terms constitute the entire agreement between you and the Company regarding your use of this Website and the products sold on this Website. If any provision of these Terms is found to be invalid or unenforceable, the remaining provisions shall remain in full force and effect.",
      "Our failure to enforce any right or provision of these Terms shall not be deemed a waiver of such right or provision.",
      "You may not assign these Terms or any of your rights or obligations hereunder without our prior written consent.",
      "These Terms are binding upon and shall inure to the benefit of both you and the Company, and your respective successors and assigns.",
    ],
  },
];
